### ISSUE TITLE
R Script Generator: cases lost in merge

### ISSUE THREAD

**Issue by sjewo** [ddionrails/tools#92] opened 2018-04-26 16:21 UTC
I think there might be a bug in the merge code returned by the R-Script Generator from paneldata.org. The sample is reduced to the cases found in the first `tmp_dataset`.
The merge function should look like this, to keep all cases from `pfad`:

```
master <- merge(master, data[["bfhgen"]], by = "bfhhnr", all.x=T, all.y=F)
```
The argument `all.x=T` keeps all cases from `pfad` respectively `master` and `all.y=F` discards any other cases.

**Comment by kwenzig** [comment] 2018-11-06 09:06
Duplicate of mhebing/ddionrails2#370 (wird damit gelöst)

**Comment by kwenzig** [comment] 2018-11-06 14:28
Duplicate of mhebing/ddionrails2#370
Will be solved, when mhebing/ddionrails2#370 is solved.

**Closed by kwenzig** 2018-11-06 14:28 UTC
